package strategy.searching;

import strategy.strategy.SortAndSearch;

/**
 * Finds the smallest element of an array after
 * sorting the contents of the array
 * @param <T> the generic type
 *
 * DO NOT EDIT THIS FILE!
 *
 * @author Josh Archer
 * @version 1.0
 */
public abstract class FindSmallest<T extends Comparable<T>> extends SortAndSearch<T>
{
    @Override
    public T find(T[] array)
    {
        sort(array);
        return array[0];
    }

    /**
     * Sorts the input array
     * @param array the array to sort
     */
    public abstract void sort(T[] array);
}
