package facade.employees;

import java.time.LocalDate;

/**
 * Information for a single employee record.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @author Josh Archer
 * @version 1.0
 */
public class Employee
{
    private int id;
    private String firstName;
    private char middleInit;
    private String lastName;
    private LocalDate hireDate;

    /**
     * Creates a new employee
     * @param id the id of the employee
     * @param firstName the first name of the employee
     * @param middleInit the middle initial of the employee
     * @param lastName the last name of the employee
     * @param hireDate the date the employee was hired
     */
    public Employee(int id, String firstName, char middleInit, String lastName, LocalDate hireDate)
    {
        this.id = id;
        this.firstName = firstName;
        this.middleInit = middleInit;
        this.lastName = lastName;
        this.hireDate = hireDate;
    }

    /**
     * Returns the id of the employee
     * @return the employee id
     */
    public int getId()
    {
        return id;
    }

    /**
     * Returns the first name of the employee
     * @return the first name
     */
    public String getFirstName()
    {
        return firstName;
    }

    /**
     * Returns the middle initial of the employee
     * @return the middle initial
     */
    public char getMiddleInit()
    {
        return middleInit;
    }

    /**
     * Returns the last name of the employee
     * @return the last name
     */
    public String getLastName()
    {
        return lastName;
    }

    /**
     * Returns the hire date of the employee
     * @return the hire date
     */
    public LocalDate getHireDate()
    {
        return hireDate;
    }

    @Override
    public String toString()
    {
        return "Employee{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", middleInit=" + middleInit +
                ", lastName='" + lastName + '\'' +
                ", hireDate=" + hireDate +
                '}';
    }
}
