package adapter.animals;

/**
 * Represents an animal.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @author Josh Archer
 * @version 1.0
 */
public class Animal
{
    private String type;
    private int avgLifeSpan;

    /**
     * Creates a new animal
     * @param type the animal type
     * @param avgLifeSpan the average life span of the animal
     */
    public Animal(String type, int avgLifeSpan)
    {
        this.type = type;
        this.avgLifeSpan = avgLifeSpan;
    }

    /**
     * Gets the animal type
     * @return the type
     */
    public String getType()
    {
        return type;
    }

    /**
     * Gets the average life span
     * @return the life span
     */
    public int getAvgLifeSpan()
    {
        return avgLifeSpan;
    }

    @Override
    public String toString()
    {
        return "Animal{" +
                "type='" + type + '\'' +
                ", avgLifeSpan=" + avgLifeSpan +
                '}';
    }
}
