package adapter.animals;
/**
 * Represents a cage that can hold an animal.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @author Josh Archer
 * @version 1.0
 */
public class Cage
{
    private Animal animal;

    /**
     * Adds an animal to the cage. Any animal
     * currently in the cage will be removed.
     * @param animal the new animal
     */
    public void addToCage(Animal animal)
    {
        emptyCage();
        this.animal = animal;
    }

    /**
     * Removes the current animal from the cage.
     */
    public void emptyCage()
    {
        if (this.animal != null)
        {
            System.out.println("You set " + this.animal.getType() + " free!");
            this.animal = null;
        }
    }
}
